# Xử lí dữ liệu

In [21]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import IPython.display as display
import math

### 1.2 Đọc tập dữ liệu

In [22]:
data_path  = "../data/pima-indians-diabetes.csv"
data_names = ["Pregnant","2Hr_Gluco_Concentrate","Blood_Pressure","Skin_Fold","2Hr_Isnulin","BMI","Predigy","Age","Class"]
df = pd.read_csv(data_path, names = data_names)

In [23]:
df.describe()

,Pregnant,2Hr_Gluco_Concentrate,Blood_Pressure,Skin_Fold,2Hr_Isnulin,BMI,Predigy,Age,Class
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

### 1.3 Xử lí dữ liệu thiếu

In [24]:
df["2Hr_Gluco_Concentrate"] = df["2Hr_Gluco_Concentrate"].replace(0, np.nan)
df["2Hr_Gluco_Concentrate"] = df["2Hr_Gluco_Concentrate"].fillna(df["2Hr_Gluco_Concentrate"].median())
df["Blood_Pressure"] = df["Blood_Pressure"].replace(0, np.nan)
df["Blood_Pressure"] = df.groupby("Class")["Blood_Pressure"].transform(lambda x: x.fillna(x.median()))
df["Skin_Fold"] = df["Skin_Fold"].replace(0, np.nan)
df["Skin_Fold"] = df.groupby("Class")["Skin_Fold"].transform(lambda x: x.fillna(x.median()))
df["Skin_Fold"] = df["Skin_Fold"].replace(0, np.nan)
df["Skin_Fold"] = df.groupby("Class")["Skin_Fold"].transform(lambda x: x.fillna(x.median()))
df["2Hr_Isnulin"] = df["2Hr_Isnulin"].replace(0, np.nan)
df["2Hr_Isnulin"] = df.groupby("Class")["2Hr_Isnulin"].transform(lambda x: x.fillna(x.median()))
df["BMI"] = df["BMI"].replace(0, np.nan)
df["BMI"] = df.groupby("Class")["BMI"].transform(lambda x: x.fillna(x.median()))
df.describe()

,Pregnant,2Hr_Gluco_Concentrate,Blood_Pressure,Skin_Fold,2Hr_Isnulin,BMI,Predigy,Age,Class
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,121.656250,72.389323,29.089844,141.753906,32.434635,0.471876,33.240885,0.348958
std,3.369578,30.438286,12.106039,8.890820,89.100847,6.880498,0.331329,11.760232,0.476951
min,0.000000,44.000000,24.000000,7.000000,14.000000,18.200000,0.078000,21.000000,0.000000
25%,1.000000,99.750000,64.000000,25.000000,102.500000,27.500000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,28.000000,102.500000,32.050000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,169.500000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

- Thực hiện xử lí dữ liệu thiếu theo trung vị của lớp output

### 1.4 Normalization & Standardlize

In [25]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from numpy import set_printoptions
# separate array into input and output components
Y = df["Class"]
X = df.drop("Class",axis=1)

scaler = MinMaxScaler(feature_range=(0, 1))
rescaledX = scaler.fit_transform(X)
scaler = StandardScaler().fit(X)
rescaledX = scaler.transform(X)
set_printoptions(precision=3)
X.describe()

,Pregnant,2Hr_Gluco_Concentrate,Blood_Pressure,Skin_Fold,2Hr_Isnulin,BMI,Predigy,Age
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,121.656250,72.389323,29.089844,141.753906,32.434635,0.471876,33.240885
std,3.369578,30.438286,12.106039,8.890820,89.100847,6.880498,0.331329,11.760232
min,0.000000,44.000000,24.000000,7.000000,14.000000,18.200000,0.078000,21.000000
25%,1.000000,99.750000,64.000000,25.000000,102.500000,27.500000,0.243750,24.000000
50%,3.000000,117.000000,72.000000,28.000000,102.500000,32.050000,0.372500,29.000000
75%,6.000000,140.250000,80.000000,32.000000,169.500000,36.600000,0.626250,41.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000

- Rescale các giá trị số về [0,1] và theo phân bố chuẩn

## 2. Baseline Models

### 2.1 Spilt Train-Valuate

In [26]:
from sklearn.model_selection import train_test_split
seed = 7
validation_size = 0.2
X_train, X_validation, Y_train, Y_validation = train_test_split(X, Y, test_size=validation_size, random_state=seed)

### 2.2 K_Fold Cross validation

In [27]:
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
k_fold = KFold(n_splits=10, shuffle=True, random_state=0)
#learning_rates = [0.05, 0.1, 0.25, 0.5, 0.75, 1]
names = ["KNN","RandomForest","SVC","AdaBoost"]
clf = [KNeighborsClassifier(n_neighbors = 13),
       RandomForestClassifier(n_estimators=13),
       SVC()
      ,AdaBoostClassifier()]
def model_fit():
    scoring = 'accuracy'
    best = {"model": "","score":0}
    for i,name in enumerate(names):
        score = cross_val_score(clf[i], X_train, Y_train, cv=k_fold, n_jobs=1, scoring=scoring)
        print("Score of Model",name,":",np.mean(score)*100)
        if(np.mean(score)*100>best["score"]):
            best["name"] = name
            best["model"] = clf[i]
            best["score"] = np.mean(score)*100
    return best
best = model_fit()
print("Best Model is:",best["name"],"with score:",best["score"])

Score of Model KNN : 87.45901639344262
Score of Model RandomForest : 86.47276573241672
Score of Model SVC : 85.33051295610787
Score of Model AdaBoost : 87.61501850872554
Best Model is: AdaBoost with score: 87.61501850872554

### 2.3 Đánh giá khả năng dự đoán với dữ liệu chưa từng xuất hiện

In [28]:
for model in clf:
    model.fit(X_train, Y_train)
    acc = model.score(X_validation, Y_validation)
    print("Score of Model(not tune)", model.__class__.__name__, ":", acc*100)

Score of Model(not tune) KNeighborsClassifier : 83.76623376623377
Score of Model(not tune) RandomForestClassifier : 87.66233766233766
Score of Model(not tune) SVC : 80.51948051948052
Score of Model(not tune) AdaBoostClassifier : 84.4155844155844

- Tuy KNN và AdaBoost có điểm đánh đánh giá cao nhất đối với bài toán tuy nhiên khi dự đoán đối với dữ liệu chưa có thì Adaboost và randomforest lại tốt nhất. Nên ta sẽ thực hiện tune đối với 2 model sau